import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ContextProvider from "@/context/ContextProvider";
import { Toaster } from 'react-hot-toast';
import ChatBotComponent from "@/components/ChatBotComponent";

const geistSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style>
      @import url('https://fonts.googleapis.com/css2?family=Epilogue:ital,wght@0,100..900;1,100..900&display=swap');
      </style>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <ContextProvider>
          <Header />
          {children}
          <Footer />
          <ChatBotComponent />
          <Toaster position="top-center" />
        </ContextProvider>
      </body>
    </html>
  );
}
